'\" t
.\"     Title: odgi paths
.\"    Author: Erik Garrison
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2020-05-15
.\"    Manual: odgi paths
.\"    Source: odgi 0.4.1
.\"  Language: English
.\"
.TH "ODGI_PATHS" "1" "2020-05-15" "odgi 0.4.1" "odgi paths"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
odgi_paths \- embedded path interrogation
.SH "SYNOPSIS"
.sp
\fBodgi paths\fP [\fB\-i, \-\-idx\fP=\fIFILE\fP] [\fIOPTION\fP]...
.SH "DESCRIPTION"
.sp
The odgi paths(1) command allows the investigation of paths of a given variation graph. It can calculate overlap statistics
of groupings of paths.
.SH "OPTIONS"
.SS "Graph Files IO"
.sp
\fB\-i, \-\-idx\fP=\fIFILE\fP
.RS 4
File containing the succinct variation graph to investigate the paths from. The file name usually ends with \fI.og\fP.
.RE
.sp
\fB\-O, \-\-overlaps\fP=\fIFILE\fP
.RS 4
Read in the path grouping file to generate the overlap statistics from. The file must be tab\-delimited. The first column
lists a grouping and the second the path itself. Each line has one path entry. For each group the pairwise overlap statistics
for each pairing will be calculated and printed to stdout.
.RE
.SS "Investigation Options"
.sp
\fB\-L, \-\-list\-paths\fP
.RS 4
Print the paths in the graph to stdout. Each path is printed in its own line.
.RE
.sp
\fB\-H, \-\-haplotypes\fP
.RS 4
Print to stdout the paths in an approximate binary haplotype matrix based on the graph\(cqs sort order. The output is tab\-delimited:
\fBpath.name\fP, \fBpath.length\fP, \fBnode.count\fP, \fBnode.1\fP, \fBnode.2\fP, \fBnode.n\fP. Each path entry is printed in its own line.
.RE
.sp
\fB\-D, \-\-delim\fP=\fICHAR\fP
.RS 4
The part of each path name before this delimiter is a group identifier. This parameter should only be set in combination
with [\fB\-H, \-\-haplotypes\fP]. Prints an additional, first column \fBgroup.name\fP to stdout.
.RE
.sp
\fB\-d, \-\-distance\fP
.RS 4
Provides a sparse distance matrix for paths. If [\fB\-D, \-\-delim\fP] is set, it will be path groups distances.
.RE
.sp
\fB\-f, \-\-fasta\fP
.RS 4
Print paths in FASTA format to stdout.
.RE
.SS "Threading"
.sp
\fB\-t, \-\-threads\fP=\fIN\fP
.RS 4
Number of threads to use.
.RE
.SS "Program Information"
.sp
\fB\-h, \-\-help\fP
.RS 4
Print a help message for \fBodgi paths\fP.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
Failure (syntax or usage error; parameter error; file processing failure; unexpected error).
.RE
.SH "BUGS"
.sp
Refer to the \fBodgi\fP issue tracker at \c
.URL "https://github.com/vgteam/odgi/issues" "" "."
.SH "AUTHORS"
.sp
\fBodgi paths\fP was written by Erik Garrison.
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://github.com/vgteam/odgi" "" ""
.sp
\fBGit source repository on GitHub:\fP \c
.URL "https://github.com/vgteam/odgi" "" ""
.sp
\fBGitHub organization:\fP \c
.URL "https://github.com/vgteam" "" ""
.sp
\fBDiscussion list / forum:\fP \c
.URL "https://github.com/vgteam/odgi/issues" "" ""
.SH "COPYING"
.sp
The MIT License (MIT)
.sp
Copyright (c) 2019 Erik Garrison
.sp
Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:
.sp
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
.sp
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.SH "AUTHOR"
.sp
Erik Garrison