'\" t
.\"     Title: odgi view
.\"    Author: Erik Garrison
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-04-08
.\"    Manual: odgi view
.\"    Source: odgi v0.6.0
.\"  Language: English
.\"
.TH "ODGI_VIEW" "1" "2021-04-08" "odgi v0.6.0" "odgi view"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
odgi_view \- projection of graphs into other formats
.SH "SYNOPSIS"
.sp
\fBodgi view\fP [\fB\-i, \-\-idx\fP=\fIFILE\fP] [\fIOPTION\fP]...
.SH "DESCRIPTION"
.sp
The odgi view(1) command can convert a graph in odgi format to GFAv1. It can reveal a graph\(cqs internal structures for e.g. debugging processes.
.SH "OPTIONS"
.SS "Graph Files IO"
.sp
\fB\-i, \-\-idx\fP=\fIFILE\fP
.RS 4
File containing the succinct variation graph to convert from. The file name usually ends with \fI.og\fP.
.RE
.sp
\fB\-g, \-\-to\-gfa\fP
.RS 4
Write the graph in GFAv1 format to standard output.
.RE
.SS "Summary Options"
.sp
\fB\-d, \-\-display\fP
.RS 4
Show the internal structures of a graph. Print to stdout the maximum node identifier, the minimum node identifier,
the nodes vector, the delete nodes bit vector and the path metadata, each in a separate line.
.RE
.SS "Program Information"
.sp
\fB\-h, \-\-help\fP
.RS 4
Print a help message for \fBodgi view\fP.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
Failure (syntax or usage error; parameter error; file processing failure; unexpected error).
.RE
.SH "BUGS"
.sp
Refer to the \fBodgi\fP issue tracker at \c
.URL "https://github.com/pangenome/odgi/issues" "" "."
.SH "AUTHORS"
.sp
\fBodgi view\fP was written by Erik Garrison.
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://github.com/pangenome/odgi" "" ""
.sp
\fBGit source repository on GitHub:\fP \c
.URL "https://github.com/pangenome/odgi" "" ""
.sp
\fBGitHub organization:\fP \c
.URL "https://github.com/pangenome" "" ""
.sp
\fBDiscussion list / forum:\fP \c
.URL "https://github.com/pangenome/odgi/issues" "" ""
.SH "COPYING"
.sp
The MIT License (MIT)
.sp
Copyright (c) 2019\-2021 Erik Garrison
.sp
Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:
.sp
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
.sp
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.SH "AUTHOR"
.sp
Erik Garrison