'\" t
.\"     Title: odgi viz
.\"    Author: Erik Garrison
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2020-06-23
.\"    Manual: odgi viz
.\"    Source: odgi v0.4.1
.\"  Language: English
.\"
.TH "ODGI_VIZ" "1" "2020-06-23" "odgi v0.4.1" "odgi viz"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
odgi_viz \- variation graph visualizations
.SH "SYNOPSIS"
.sp
\fBodgi viz\fP [\fB\-i, \-\-idx\fP=\fIFILE\fP] [\fB\-o, \-\-out\fP=\fIFILE\fP] [\fIOPTION\fP]...
.SH "DESCRIPTION"
.sp
The odgi viz(1) command can produce a linear, static visualization of an odgi variation graph. It can aggregate the pangenome into bins
and directly renders a raster image. The binning level can be specified in input or it is calculated from the target width of the PNG to emit.
Can be used to produce visualizations for gigabase scale pangenomes. For more information  about the binning process,
please refer to odgi bin. If reverse coloring was selected, only
the bins with a reverse rate of at least 0.5 are colored. Currently, there is no parameter to color according to the
sequence coverage in bins available.
.SH "OPTIONS"
.SS "Graph Files IO"
.sp
\fB\-i, \-\-idx\fP=\fIFILE\fP
.RS 4
File containing the succinct variation graph to convert from. The file name usually ends with \fI.og\fP.
.RE
.sp
\fB\-o, \-\-out\fP=\fIFILE\fP
.RS 4
Write the visualization in PNG format to this file.
.RE
.SS "Visualization Options"
.sp
\fB\-x, \-\-width\fP=\fIN\fP
.RS 4
Set the width in pixels of the output image.
.RE
.sp
\fB\-y, \-\-height\fP=\fIN\fP
.RS 4
Set the height in pixels of the output image.
.RE
.sp
\fB\-P, \-\-path\-height\fP=\fIN\fP
.RS 4
The height in pixels for a path.
.RE
.sp
\fB\-X, \-\-path\-x\-padding\fP=\fIN\fP
.RS 4
The padding in pixels on the x\-axis for a path.
.RE
.sp
\fB\-R, \-\-path\-per\-row\fP
.RS 4
Display a single path per row rather than packing them.
.RE
.sp
\fB\-L, \-\-link\-path\-pieces\fP=\fIFLOAT\fP
.RS 4
Show thin links of this relative width to connect path pieces.
.RE
.sp
\fB\-A, \-\-alignment\-prefix\fP=\fISTRING\fP
.RS 4
Apply alignment related visual motifs to paths which have this name prefix.
.RE
.sp
\fB\-S, \-\-show\-strand\fP
.RS 4
Use red and blue coloring to display forward and reverse alignments. This parameter should only be set in combination with
[\fB\-A, \-\-alignment\-prefix\fP=\fISTRING\fP].
.RE
.SS "Binned Mode Options"
.sp
\fB\-b, \-\-binned\-mode\fP=\fIN\fP
.RS 4
The variation graph is binned before its visualization. Each pixel in the output image will correspond to a bin.
For more information about the binning process, please refer to odgi bin.
.RE
.sp
\fB\-w, \-\-bin\-width\fP=\fIN\fP
.RS 4
The bin width specifies the size of each bin in the binned mode. If it is not specified, the bin width is calculated
from the width in pixels of the output image.
.RE
.sp
\fB\-g, \-\-no\-gap\-links\fP
.RS 4
We divide links into 2 classes:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Class: The links which help to follow complex variations. They need to be drawn, else one could not follow
the sequence of a path.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 2." 4.2
.\}
Class: The links helping to follow simple variations. Such links solely connecting a path from left to right may not
be relevant to understand a path\(cqs traversal through the bins. Therefore, they are not drawn in the binned mode.
.RE
.RE
.SS "Threading"
.sp
\fB\-t, \-\-threads\fP=\fIN\fP
.RS 4
Number of threads to use.
.RE
.SS "Program Information"
.sp
\fB\-h, \-\-help\fP
.RS 4
Print a help message for \fBodgi viz\fP.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
Failure (syntax or usage error; parameter error; file processing failure; unexpected error).
.RE
.SH "BUGS"
.sp
Refer to the \fBodgi\fP issue tracker at \c
.URL "https://github.com/vgteam/odgi/issues" "" "."
.SH "AUTHORS"
.sp
\fBodgi viz\fP was written by Erik Garrison.
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://github.com/vgteam/odgi" "" ""
.sp
\fBGit source repository on GitHub:\fP \c
.URL "https://github.com/vgteam/odgi" "" ""
.sp
\fBGitHub organization:\fP \c
.URL "https://github.com/vgteam" "" ""
.sp
\fBDiscussion list / forum:\fP \c
.URL "https://github.com/vgteam/odgi/issues" "" ""
.SH "COPYING"
.sp
The MIT License (MIT)
.sp
Copyright (c) 2019 Erik Garrison
.sp
Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:
.sp
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
.sp
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.SH "AUTHOR"
.sp
Erik Garrison