'\" t
.\"     Title: odgi unchop
.\"    Author: Erik Garrison, Andrea Guarracino
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-04-01
.\"    Manual: odgi unchop
.\"    Source: odgi v0.6.0
.\"  Language: English
.\"
.TH "ODGI_UNCHOP" "1" "2021-04-01" "odgi v0.6.0" "odgi unchop"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
odgi_unchop \- merge unitigs into single nodes
.SH "SYNOPSIS"
.sp
\fBodgi unchop\fP [\fB\-i, \-\-idx\fP=\fIFILE\fP] [\fB\-o, \-\-out\fP=\fIFILE\fP] [\fIOPTION\fP]...
.SH "DESCRIPTION"
.sp
The odgi unchop(1) command merges each unitig into a single node preserving the node order.
.SH "OPTIONS"
.SS "Graph Files IO"
.sp
\fB\-i, \-\-idx\fP=\fIFILE\fP
.RS 4
File containing the succinct variation graph to unchop. The file name usually ends with \fI.og\fP.
.RE
.sp
\fB\-o, \-\-out\fP=\fIFILE\fP
.RS 4
Write the unchopped dynamic succinct variation graph to this file. A file ending with \fI.og\fP is recommended.
.RE
.SS "Processing Information"
.sp
\fB\-d, \-\-debug\fP
.RS 4
Print information about the process to stderr.
.RE
.SS "Threading"
.sp
\fB\-t, \-\-threads\fP=\fIN\fP
.RS 4
Number of threads to use for the parallel operations.
.RE
.SS "Program Information"
.sp
\fB\-h, \-\-help\fP
.RS 4
Print a help message for \fBodgi unchop\fP.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
Failure (syntax or usage error; parameter error; file processing failure; unexpected error).
.RE
.SH "BUGS"
.sp
Refer to the \fBodgi\fP issue tracker at \c
.URL "https://github.com/pangenome/odgi/issues" "" "."
.SH "AUTHORS"
.sp
\fBodgi unchop\fP was written by Erik Garrison and Andrea Guarracino.
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://github.com/pangenome/odgi" "" ""
.sp
\fBGit source repository on GitHub:\fP \c
.URL "https://github.com/pangenome/odgi" "" ""
.sp
\fBGitHub organization:\fP \c
.URL "https://github.com/pangenome" "" ""
.sp
\fBDiscussion list / forum:\fP \c
.URL "https://github.com/pangenome/odgi/issues" "" ""
.SH "COPYING"
.sp
The MIT License (MIT)
.sp
Copyright (c) 2019\-2021 Erik Garrison
.sp
Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:
.sp
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
.sp
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.SH "AUTHOR"
.sp
Erik Garrison, Andrea Guarracino