= odgi build(1)
ifdef::backend-manpage[]
Erik Garrison
:doctype: manpage
:release-version: 0.3
:man manual: odgi build
:man source: odgi 0.3
:page-layout: base
endif::[]

== NAME

odgi_build - construct a dynamic succinct variation graph

== SYNOPSIS

*odgi build* [*-g, --gfa*=_FILE_] [*-o, --out*=_FILE_] [_OPTION_]...

== DESCRIPTION

The odgi build(1) command constructs a succinct variation graph from a GFA. Currently, only GFA1 is supported. For details of the format please see https://github.com/GFA-spec/GFA-spec/blob/master/GFA1.md.

== OPTIONS

=== Graph Files IO

*-g, --gfa*=_FILE_::
  GFA1 file containing the nodes, edges and paths to build a dynamic succinct variation graph from.

*-o, --out*=_FILE_::
  Write the dynamic succinct variation graph to this file. A file ending with _.og_ is recommended.

=== Graph Sorting

*-s, --sort*::
  Apply a general topological sort to the graph and order the node ids accordingly. A bidirected adaptation of Kahn's topological sort (1962) is used, which can handle components with no heads or tails. Here, both heads and tails are taken into account.

=== Processing Information

*-p, --progress*::
  Print progress updates to stdout.

*-d, --debug*::
  Verbosely print graph information to stderr. This includes the maximum node_id, the minimum node_id, the handle to node_id mapping, the deleted nodes and the path metadata.

*--trace*::
  Include backtrace information when reporting errors.

*-v, --verbose*::
  Verbosely print processing information to stderr, including debug-level log messages.

*-w, --warnings*::
  Turn on script warnings (applies to executed code).

*-t, --timings*::
  Print timings report to stderr (time to read, parse, and convert).

=== Program Information

*-h, --help*::
  Print a help message for *odgi build*.

== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/vgteam/odgi/issues.

== AUTHORS

*odgi build* was written by Erik Garrison.

== RESOURCES

*Project web site:* https://github.com/vgteam/odgi

*Git source repository on GitHub:* https://github.com/vgteam/odgi

*GitHub organization:* https://github.com/vgteam

*Discussion list / forum:* https://github.com/vgteam/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.