= odgi stats(1)
ifdef::backend-manpage[]
Erik Garrison, Andrea Guarracino
:doctype: manpage
:release-version: v0.6.0
:man manual: odgi stats
:man source: odgi v0.6.0
:page-layout: base
endif::[]

== NAME

odgi_stats - metrics describing variation graphs

== SYNOPSIS

*odgi stats* [*-i, --idx*=_FILE_] [_OPTION_]...

== DESCRIPTION

The odgi stats(1) command produces statistics of a variation graph. Among other metrics, it can calculate the #nodes, #edges, #paths and the total nucleotide length of the graph. Various histogram summary options complement the tool. If [*-B, --bed-multicov*=_BED_] is set, the metrics will be produced for the intervals specified in the BED.

== OPTIONS

=== Graph Files IO

*-i, --idx*=_FILE_::
  File containing the succinct variation graph to create statistics from. The file name usually ends with _.og_.


=== Summary Options

*-S, --summarize*::
  Summarize the graph properties and dimensions. Print to stdout the #nucleotides, #nodes, #edges and #paths of the graph.

*-W, --weak-connected-components*::
  Shows the properties of the weakly connected components.

*-b, --base-content*::
  Describe the base content of the graph. Print to stdout the #A, #C, #G and #T of the graph.

//*-C, --coverage*::
//  Provide a histogram of path coverage over bases in the graph. Print three tab-delimited columns to stdout: *type*, *cov*, *N*. *type* is one of _full_ or _uniq_ and determines if the histogram corresponds to the full graph or only to a unique paths graph. *cov* implies the #paths. *N* implies the #nucleotides.
//
//*-V, --set-coverage*::
//  Provide a histogram of coverage over unique set of paths. Print two tab-delimited columns to stdout: *cov*, *sets*. *cov* implies #nucleotides. *sets* lists the unique set of paths in a comma separated list. Sets with a *cov* of one and no paths in *sets* are listed, too.
//
//*-M, --multi-coverage*::
//  Provide a histogram of coverage over unique multiset, the combination with possible repetition of paths. Print two tab-delimited columns to stdout: *cov*, *sets*. *cov* implies #nucleotides. *sets* lists the unique multisets of paths in a comma separated list. Multisets with a *cov* of one and no paths in *sets* are listed, too.
//
//
//=== BED Interval
//
//*-B, --bed-multicov*=_BED_::
//  For each BED entry, provide a table of path coverage over unique multisets of paths in the graph. Each unique multiset of paths overlapping a given BED interval is described in terms of its length relative to the total interval, the number of path traversals and unique paths involved in these traversals.


=== Sorting goodness evaluation

*-l, --mean-links-length*::
  Calculate the mean links length. This metric is path-guided and computable in 1D and 2D.

*-g, --no-gap-links*::
  Don't penalize gap links in the mean links length. A gap link is a link which connects two nodes that are consecutive in the linear pangenomic order. This option is specifiable only to compute the mean links length in 1D.

*-s, --sum-path-nodes-distances*::
  Calculate the sum of path nodes distances. This metric is path-guided and computable in 1D and 2D. For each path, it iterates from node to node, summing their distances, and normalizing by the path length. In 1D, if a link goes back in the linearized viewpoint of the graph, this is penalized (adding 3 times its length in the sum).

*-d, --penalize-different-orientation*::
  If a link connects two nodes which have different orientations, this is penalized (adding 2 times its length in the sum).

*-c, --coords-in*::
  File containing the layout coordinates of the succinct variation graph specified as input. The file name usually ends with _.lay_. When the layout coordinates are provided, the mean links length and the sum path nodes distances statistics are evaluated in 2D, else in 1D.

*-P, --path-statistics*::
  Display the statistics (mean links length or sum path nodes distances) for each path.


=== Threading

*-t, --threads*=_N_::
  Number of threads to use.

=== Program Information

*-h, --help*::
  Print a help message for *odgi stats*.

== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/vgteam/odgi/issues.

== AUTHORS

*odgi stats* was written by Erik Garrison and Andrea Guarracino.

ifdef::backend-manpage[]
== RESOURCES

*Project web site:* https://github.com/vgteam/odgi

*Git source repository on GitHub:* https://github.com/vgteam/odgi

*GitHub organization:* https://github.com/vgteam

*Discussion list / forum:* https://github.com/vgteam/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019-2021 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]