= odgi sort(1)
ifdef::backend-manpage[]
Erik Garrison
:doctype: manpage
:release-version: 0.3
:man manual: odgi build
:man source: odgi 0.3
:page-layout: base
endif::[]

== NAME

odgi_sort - sort a variation graph

== SYNOPSIS

*odgi sort* [*-i, --idx*=_FILE_] [_OPTION_]...

== DESCRIPTION

The odgi sort(1) command produces sorts a succinct a variation graph. Topological sorts... TODO. A chunk size specifies how much
of the graph to grab at once in each topological sorting phase. The sorting algorithm will continue the sort from the
next node in the prior graph order that has not been sorted, yet.

== OPTIONS

=== Graph Files IO

*-i, --idx*=_FILE_::
  File containing the succinct variation graph to sort. The file name usually ends with _.og_.

*-o, --out*=_FILE_::
  Write the sorted dynamic succinct variation graph to this file. A file ending with _.og_ is recommended.

*-s, --sort-order*=_FILE_::
  File containing the sort order. Each line contains one node identifier.

=== Topological Sorts

*-b, --breadth-first*::
  Use a (chunked) breadth first topological sort.

*-B, --breadth-first-chunk*=_N_::
  Chunk size for breadth first topological sort. Specify how many nucleotides to grap at once in each BFS phase.

*-z, --depth-first*::
  Use a (chunked) depth first topological sort.

*-Z, --depth-first-chunk*::
  Chunk size for the depth first topological sort. Specify how many nucleotides to grap at once in each DFS phace.

=== Random Sort

=== Moondrian Sort

=== 1D SGD Sort

=== Path Options

=== Additional Parameters

*-d, --dagify-sort*::
  Sort on the basis of a DAGified graph.

*-c, --cycle-breaking*::
  Use a cycle breaking sort.

*-e, --eades*::
  Use eades algorithm.

=== Threading

*-t, --threads*=_N_::
  Number of threads to use for parallel sorting in SGD. Only specify this argument in combination with *-S, --linear-sgd*. No multi-threading support for any other sorting algorithm.

=== Processing Information

*-P, --progress*::
  Print sort progress to stdout.

=== Program Information

*-h, --help*::
  Print a help message for *odgi sort*.

== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/vgteam/odgi/issues.

== AUTHORS

*odgi sort* was written by Erik Garrison.
ifdef::backend-manpage[]
== RESOURCES

*Project web site:* https://github.com/vgteam/odgi

*Git source repository on GitHub:* https://github.com/vgteam/odgi

*GitHub organization:* https://github.com/vgteam

*Discussion list / forum:* https://github.com/vgteam/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]