= odgi depth(1)
ifdef::backend-manpage[]
Andrea Guarracino
:doctype: manpage
:release-version: v0.6.0
:man manual: odgi depth
:man source: odgi v0.6.0
:page-layout: base
endif::[]

== NAME

odgi_depth - find the depth of graph as defined by query criteria


== SYNOPSIS

*odgi depth* [*-i, --input*=_FILE_] [_OPTION_]...

== DESCRIPTION

The odgi depth(1) command finds the depth of graph as defined by query criteria.


== OPTIONS

=== Graph Files IO

*-i, --input*=_FILE_::
  Compute path depths in this graph.


=== Depth Options

*-s, --subset-paths*=_FILE_::
  Compute the depth considering only the paths specified in the FILE; the file must contain one path name per line and a
  subset of all paths can be specified.

*-r, --path*=_STRING_::
  Compute the depth of the given path in the graph

*-R, --paths*=_FILE_::
  Compute depth for the paths listed in FILE.

*-g, --graph-pos*=_[[node_id][,offset[,(+|-)]*]*]_::
  Compute the depth at the given node, e.g. 7 or 3,4 or 42,10,+ or 302,0,-.

*-G, --graph-pos-file*=_FILE_::
  A file with graph path position per line.

*-p, --path-pos*=_[[path_name][,offset[,(+|-)]*]*]_::
  Return depth at the given path position e.g. chrQ or chr3,42 or chr8,1337,+ or chrZ,3929,-.

*-F, --path-pos-file*=_FILE_::
  A file with one path position per line.

*-b, --bed-input*=_FILE_::
  A BED file of ranges in paths in the graph.

*-d, --graph-depth*::
  Compute the depth on each node in the graph.

*-d, --search-radius*=_STRING_::
  Limit coordinate conversion breadth-first search up to DISTANCE bp from each given position [default: 10000].


=== Threading

*-t, --threads*=_N_::
  Number of threads to use.


=== Program Information

*-h, --help*::
  Print a help message for *odgi depth*.


== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/vgteam/odgi/issues.

== AUTHORS

*odgi depth* was written by Andrea Guarracino.

ifdef::backend-manpage[]
== RESOURCES

*Project web site:* https://github.com/vgteam/odgi

*Git source repository on GitHub:* https://github.com/vgteam/odgi

*GitHub organization:* https://github.com/vgteam

*Discussion list / forum:* https://github.com/vgteam/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]