= odgi position(1)
ifdef::backend-manpage[]
Erik Garrison
:doctype: manpage
:release-version: v0.6.0
:man manual: odgi position
:man source: odgi v0.6.0
:page-layout: base
endif::[]

== NAME

odgi_position - position parts of the graph as defined by query criteria


== SYNOPSIS

*odgi position* [*-i, --target*=_FILE_] [_OPTION_]...

== DESCRIPTION

The odgi position(1) command translates positions and coordinate ranges between nodes and embedded paths.
It provides liftover functionality, allowing us to translate a position between any reference paths embedded in the `-i, --target` graph.
We can additionally project coordinates and annotations from a source graph `-x, --source` into the `target`.
When completing this "graph lift", the intersecting set of paths in the two graphs are used to complete the coordinate projection.

== OPTIONS

=== Graph Files IO

*-i, --target*=_FILE_::
  Describe positions in this graph.

*-x, --source*=_FILE_::
  Translate positions from this graph into the target graph using common `--lift-paths` shared between both graphs [default: use the same source/target
graph]


=== Position Options

*-r, --ref-paths*=_STRING_::
  Translate the given positions into positions relative to this reference path.

*-R, --ref-paths*=_FILE_::
  Use the ref-paths in FILE.

*-l, --lift-path*=_STRING_::
  Lift positions from `--source` to `--target` via coordinates in this path common to both graphs [default: all common paths
between `--source` and `--target`].

*-g, --graph-pos*=_[[node_id][,offset[,(+|-)]*]*]_::
  A graph position, e.g. 42,10,+ or 302,0,-.

*-F, --path-pos-file*=_FILE_::
  A file with one path position per line.

*-b, --bed-input*=_FILE_::
  A BED file of ranges in paths in the graph to lift into the target graph `-v`, `--give-graph-pos` emit graph positions.

*-v, --give-graph-pos*::
  Emit graph positions (node,offset,strand) rather than path positions.


*-d, --search-radius*=_STRING_::
  Limit coordinate conversion breadth-first search up to DISTANCE bp from each given position [default: 10000].


=== Threading

*-t, --threads*=_N_::
  Number of threads to use.


=== Program Information

*-h, --help*::
  Print a help message for *odgi position*.


== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/vgteam/odgi/issues.

== AUTHORS

*odgi position* was written by Erik Garrison.

ifdef::backend-manpage[]
== RESOURCES

*Project web site:* https://github.com/vgteam/odgi

*Git source repository on GitHub:* https://github.com/vgteam/odgi

*GitHub organization:* https://github.com/vgteam

*Discussion list / forum:* https://github.com/vgteam/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019-2021 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]
