= odgi unitig(1)
ifdef::backend-manpage[]
Erik Garrison
:doctype: manpage
:release-version: v0.4.1 
:man manual: odgi unitig
:man source: odgi v0.4.1 
:page-layout: base
endif::[]

== NAME

odgi_unitig - output unitigs of the graph

== SYNOPSIS

*odgi unitig* [*-i, --idx*=_FILE_] [_OPTION_]...

== DESCRIPTION

The odgi unitig(1) command can print all https://github.com/mcveanlab/mccortex/wiki/unitig[unitigs] of a given odgi graph to standard output in FASTA format. Unitigs can also be emitted
in a fixed sequence quality FASTQ format. Various parameters can refine the unitigs to print.

== OPTIONS

=== Graph Files IO

*-i, --idx*=_FILE_::
  File containing the succinct variation graph to convert from. The file name usually ends with _.og_.

=== FASTQ Options

*-f, --fake-fastq*::
  Write the unitigs in FASTQ format to stdout with a fixed quality value of _I_.

=== Unitig Options

*-t, --sample-to*=_N_::
  Continue unitigs with a random walk in the graph so that they have at least the given _N_ length.

*-p, --sample-plus*=_N_::
  Continue unitigs with a random walk in the graph by _N_ past their natural end.

*-l, --min-begin-node-length*=_N_::
  Only begin unitigs collection from nodes which have at least length _N_.

=== Program Information

*-h, --help*::
  Print a help message for *odgi unitig*.

== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/vgteam/odgi/issues.

== AUTHORS

*odgi unitig* was written by Erik Garrison.

ifdef::backend-manpage[]
== RESOURCES

*Project web site:* https://github.com/vgteam/odgi

*Git source repository on GitHub:* https://github.com/vgteam/odgi

*GitHub organization:* https://github.com/vgteam

*Discussion list / forum:* https://github.com/vgteam/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]