= odgi degree(1)
ifdef::backend-manpage[]
Erik Garrison
:doctype: manpage
:release-version: v0.6.0
:man manual: odgi degree
:man source: odgi v0.6.0
:page-layout: base
endif::[]


== NAME

odgi_degree - describe the graph in terms of node degree

== SYNOPSIS

*odgi degree* [*-i, --idx*=_FILE_] [_OPTION_]...

== DESCRIPTION

The odgi degree(1) command describes the graph in terms of node degree. For the input graph, it shows the node.count, edge.count, avg.degree, min.degree, and max.degree.


== OPTIONS

=== Graph Files IO

*-i, --idx*=_FILE_::
  Describe node degree in this graph. The file name usually ends with _.og_.


=== Summary Options

*-S, --summarize*::
  Summarize the graph properties and dimensions. Print to stdout the node.id and the node.degree.


=== Threading

*-t, --threads*=_N_::
  Number of threads to use.


=== Program Information

*-h, --help*::
  Print a help message for *odgi degree*.


== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/pangenome/odgi/issues.

== AUTHORS

*odgi degree* was written by Erik Garrison.

ifdef::backend-manpage[]
== RESOURCES

*Project web site:* https://github.com/pangenome/odgi

*Git source repository on GitHub:* https://github.com/pangenome/odgi

*GitHub organization:* https://github.com/pangenome

*Discussion list / forum:* https://github.com/pangenome/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019-2021 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]