= odgi bin(1)
ifdef::backend-manpage[]
Erik Garrison
:doctype: manpage
:release-version: v0.4.1 
:man manual: odgi bin
:man source: odgi v0.4.1 
:page-layout: base
endif::[]

== NAME

odgi_bin - binning of pangenome sequence and path information in the graph

== SYNOPSIS

*odgi bin* [*-i, --idx*=_FILE_] [_OPTION_]...

== DESCRIPTION

The odgi bin(1) command bins a given variation graph. The pangenome sequence, the one-time traversal of all nodes from smallest to
largest node identifier, can be summed up into bins of a specified size. For each bin, the path metainformation is summarized.
This enables a summarized view of gigabase scale graphs. Each step of a path is a bin and connected to its next bin via a link.
A link has a start bin identifier and an end bin identifier. +
The concept of odgi bin is also applied in odgi <<odgi_viz.adoc#_odgi_viz1, viz>>.
A demonstration of how the odgi bin JSON output can be used for an interactive visualization is realized in the https://graph-genome.github.io/[Pantograph]
project. Per default, odgi bin writes the bins to stdout in a tab-delimited format: *path.name*, *path.prefix*, *path.suffix*,
*bin* (bin identifier), *mean.cov* (mean coverage of the path in this bin), *mean.inv* (mean inversion rate of this path in this bin),
*mean.pos* (mean nucleotide position of this path in this bin), *first.nucl* (first nucleotide position of this path in this bin),
*last.nucl* (last nucleotide position of this path in this bin). These nucleotide ranges might span positions that are not present in the bin. Example:
A range of 1-100 means that the first nucleotide has position 1 and the last has position 100, but nucleotide 45 could be located in
another bin. For an exact positional output, please specify [*-j, --json*].

== OPTIONS

=== Graph Files IO

*-i, --idx*=_FILE_::
  File containing the succinct variation graph to investigate the bin from. The file name usually ends with _.og_.

=== FASTA Options

*-f, --fasta*=_FILE_::
  Write the pangenome sequence to _FILE_ in FASTA format.

=== Bin Options

*-n, --number-bins*=_N_::
  The number of bins the pangenome sequence should be chopped up to.

*-w, --bin-width*=_N_::
  The bin width specifies the size of each bin.

*-D, --path-delim*=_STRING_::
  Annotate rows by prefix and suffix of this delimiter.

*-a, --aggregate-delim*::
  Aggregate on path prefix delimiter. Argument depends on [*-D, --path-delim*=_STRING_].

*-j, --json*::
  Print bins and links to stdout in pseudo JSON format. Each line is a valid JSON object, but the whole file is not a valid JSON!
  First, each bin including its pangenome sequence is printed to stdout per line. Second, for each path in the graph, its
  traversed bins including metainformation: *bin* (bin identifier), *mean.cov* (mean coverage of the path in this bin), *mean.inv* (mean inversion rate of this path in this bin),
  *mean.pos* (mean nucleotide position of this path in this bin), and an array of ranges determining the nucleotide position
  of the path in this bin. Switching first and last nucleotide in a range represents a complement reverse
  orientation of that particular sequence.

*-s, --no-seqs*::
  If [*-j, --json*] is set, no nucleotide sequences will be printed to stdout in order to save disk space.

*-g, --no-gap-links*::
  Links connecting a path from left to right may not be relevant to understand a path's traversal through the bins. They
  can be left out saving disk space.

=== Program Information

*-h, --help*::
  Print a help message for *odgi bin*.

== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/vgteam/odgi/issues.

== AUTHORS

*odgi bin* was written by Erik Garrison.

ifdef::backend-manpage[]
== RESOURCES

*Project web site:* https://github.com/vgteam/odgi

*Git source repository on GitHub:* https://github.com/vgteam/odgi

*GitHub organization:* https://github.com/vgteam

*Discussion list / forum:* https://github.com/vgteam/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]