= odgi prune(1)
ifdef::backend-manpage[]
Erik Garrison
:doctype: manpage
:release-version: v0.4.1 
:man manual: odgi prune
:man source: odgi v0.4.1 
:page-layout: base
endif::[]

== NAME

odgi_prune - remove complex parts of the graph

== SYNOPSIS

*odgi prune* [*-i, --idx*=_FILE_] [*-o, --out*=_FILE_] [_OPTION_]...

== DESCRIPTION

The odgi prune(1) command can remove complex parts of a graph. One can drop paths, nodes by a certain kind of edge coverage,
edges and graph tips. Specifying a kmer length and a maximum number of furcations, the graph can be broken at edges not
fitting into these conditions.

== OPTIONS

=== Graph Files IO

*-i, --idx*=_FILE_::
  File containing the succinct variation graph to load in. The file name usually ends with _.og_.

*-o, --out*=_FILE_::
  Write the pruned graph to _FILE_. The file name should end with _.og_.

=== Kmer Options

*-k, --kmer-length*=_N_::
  The length of the kmers to consider.

*-e, --max-furcations*=_N_::
  Break at edges that would induce _N_ many furcations in a kmer.

=== Node Options

*-d, --max-degree*=_N_::
  Remove nodes that have a higher node degree than _N_.

*-c, --min-coverage*=_N_::
  Remove nodese covered by fewer than _N_ number of path steps.

*-C, --max-coverage*=_N_::
  Remove nodes covered by more than _N_ number of path steps.

*-T, --cut-tips*=_N_::
  Remove nodes which are graph tips.

=== Edge Options

*-E, --edge-coverage*::
  Remove edges outside of the minimum and maximum coverage rather than nodes. Only set this argument in combination with
  [*-c, --min-coverage*=_N_] and [*-C, --max-coverage*=_N_].

*-b, --best-edges*=_N_::
  Only keep the _N_ most covered inbound and output edges of each node.

=== Path Options

*-D, --drop-paths*::
  Remove the paths from the graph.

=== Threading

*-t, --threads*=_N_::
  Number of threads to use.

=== Program Information

*-h, --help*::
  Print a help message for *odgi prune*.

== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/vgteam/odgi/issues.

== AUTHORS

*odgi prune* was written by Erik Garrison.

ifdef::backend-manpage[]
== RESOURCES

*Project web site:* https://github.com/vgteam/odgi

*Git source repository on GitHub:* https://github.com/vgteam/odgi

*GitHub organization:* https://github.com/vgteam

*Discussion list / forum:* https://github.com/vgteam/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]