= odgi version(1)
ifdef::backend-manpage[]
Simon Heumos
:doctype: manpage
:release-version: v0.6.0
:man manual: odgi version
:man source: odgi v0.6.0
:page-layout: base
endif::[]

== NAME

odgi_version - display the version of odgi

== SYNOPSIS

*odgi version* [_OPTION_]...

== DESCRIPTION

The odgi version(1) command prints the current git version with tags and codename to stdout (like _v-44-g89d022b "back to old ABI"_). Optionally, only the release, version or codename can be printed.

== OPTIONS

=== Version Options

*-v, --version*=::
  Print only the version (like _v-44-g89d022b_).

*-c, --codename*::
  Print only the codename (like _back to old ABI_).

*-r, --release*::
  Print only the release (like _v_).

=== Program Information

*-h, --help*::
  Print a help message for *odgi version*.

== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/vgteam/odgi/issues.

== AUTHORS

*odgi version* was written by Simon Heumos.

ifdef::backend-manpage[]
== RESOURCES

*Project web site:* https://github.com/vgteam/odgi

*Git source repository on GitHub:* https://github.com/vgteam/odgi

*GitHub organization:* https://github.com/vgteam

*Discussion list / forum:* https://github.com/vgteam/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]