= odgi paths(1)
ifdef::backend-manpage[]
Erik Garrison
:doctype: manpage
:release-version: v0.6.0
:man manual: odgi paths
:man source: odgi v0.6.0
:page-layout: base
endif::[]

== NAME

odgi_paths - embedded path interrogation

== SYNOPSIS

*odgi paths* [*-i, --idx*=_FILE_] [_OPTION_]...

== DESCRIPTION

The odgi paths(1) command allows the investigation of paths of a given variation graph. It can calculate overlap statistics
of groupings of paths.

== OPTIONS

=== Graph Files IO

*-i, --idx*=_FILE_::
  File containing the succinct variation graph to investigate the paths from. The file name usually ends with _.og_.

*-O, --overlaps*=_FILE_::
  Read in the path grouping file to generate the overlap statistics from. The file must be tab-delimited. The first column
  lists a grouping and the second the path itself. Each line has one path entry. For each group the pairwise overlap statistics
  for each pairing will be calculated and printed to stdout.

=== Investigation Options

*-L, --list-paths*::
  Print the paths in the graph to stdout. Each path is printed in its own line.

*-H, --haplotypes*::
  Print to stdout the paths in an approximate binary haplotype matrix based on the graph's sort order. The output is tab-delimited:
  *path.name*, *path.length*, *node.count*, *node.1*, *node.2*, *node.n*. Each path entry is printed in its own line.

*-D, --delim*=_CHAR_::
  The part of each path name before this delimiter is a group identifier. This parameter should only be set in combination
  with [*-H, --haplotypes*]. Prints an additional, first column *group.name* to stdout.

*-d, --distance*::
  Provides a sparse distance matrix for paths. If [*-D, --delim*] is set, it will be path groups distances.

*-f, --fasta*::
  Print paths in FASTA format to stdout.

=== Threading

*-t, --threads*=_N_::
  Number of threads to use.

=== Program Information

*-h, --help*::
  Print a help message for *odgi paths*.

== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/pangenome/odgi/issues.

== AUTHORS

*odgi paths* was written by Erik Garrison.

ifdef::backend-manpage[]
== RESOURCES

*Project web site:* https://github.com/pangenome/odgi

*Git source repository on GitHub:* https://github.com/pangenome/odgi

*GitHub organization:* https://github.com/pangenome

*Discussion list / forum:* https://github.com/pangenome/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019-2021 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]