= odgi kmers(1)
ifdef::backend-manpage[]
Erik Garrison
:doctype: manpage
:release-version: v0.6.0
:man manual: odgi kmers
:man source: odgi v0.6.0
:page-layout: base
endif::[]

== NAME

odgi_kmers - show and characterize the kmer space of the graph

== SYNOPSIS

*odgi kmers* [*-i, --idx*=_FILE_] [*-c, --stdout*] [_OPTION_]...

== DESCRIPTION

Given a kmer length, the odgi kmers(1) command can emit all kmers. The output can be refined by setting the maximum number
of furcations at edges or by not considering nodes above a given node degree limit.

== OPTIONS

=== Graph Files IO

*-i, --idx*=_FILE_::
  File containing the succinct variation graph to convert from. The file name usually ends with _.og_.

*-c, --stdout*=::
  Write the kmers to standard output. Kmers are line-separated.

=== Kmer Options

*-k, --kmer-length*=_N_::
  The kmer length to generate kmers from.

*-e, --max-furcations*=_N_::
  Break at edges that would induce this many furcations when generating a kmer.

*-D, --max-degree*=_N_::
  Don't take nodes into account that have a degree greater than _N_.

=== Threading

*-t, --threads*=_N_::
  Number of threads to use.

=== Program Information

*-h, --help*::
  Print a help message for *odgi kmers*.

== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/vgteam/odgi/issues.

== AUTHORS

*odgi kmers* was written by Erik Garrison.

ifdef::backend-manpage[]
== RESOURCES

*Project web site:* https://github.com/vgteam/odgi

*Git source repository on GitHub:* https://github.com/vgteam/odgi

*GitHub organization:* https://github.com/vgteam

*Discussion list / forum:* https://github.com/vgteam/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]