= odgi chop(1)
ifdef::backend-manpage[]
Erik Garrison
:doctype: manpage
:release-version: v0.4.1 
:man manual: odgi chop
:man source: odgi v0.4.1 
:page-layout: base
endif::[]

== NAME

odgi_chop - divide nodes into smaller pieces

== SYNOPSIS

*odgi chop* [*-i, --idx*=_FILE_] [*-o, --out*=_FILE_] [*-c, --chop-to*=_N_] [_OPTION_]...

== DESCRIPTION

The odgi chop(1) command chops long nodes into short ones while preserving the graph topology.

== OPTIONS

=== Graph Files IO

*-i, --idx*=_FILE_::
  File containing the succinct variation graph to chop. The file name usually ends with _.og_.

*-o, --out*=_FILE_::
  Write the choped succinct variation graph to _FILE_. The file name usually ends with _.og_.

=== Chop Options

*-c, --chop-to*=_N_::
  Divide nodes that longer than _N_ into nodes no longer than _N_ while maintaining graph topology.

=== Processing Information

*-d, --debug*::
  Print information about the components to stdout.

=== Program Information

*-h, --help*::
  Print a help message for *odgi chop*.

== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/vgteam/odgi/issues.

== AUTHORS

*odgi chop* was written by Erik Garrison.

ifdef::backend-manpage[]
== RESOURCES

*Project web site:* https://github.com/vgteam/odgi

*Git source repository on GitHub:* https://github.com/vgteam/odgi

*GitHub organization:* https://github.com/vgteam

*Discussion list / forum:* https://github.com/vgteam/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]