= odgi extract(1)
ifdef::backend-manpage[]
Andrea Guarracino
:doctype: manpage
:release-version: v0.6.0
:man manual: odgi extract
:man source: odgi v0.6.0
:page-layout: base
endif::[]

== NAME

odgi_extract - extract parts of the graph as defined by query criteria


== SYNOPSIS

*odgi extract* [*-f, --input-graphs*=_FILE_] [*-o, --out*=_FILE_] [_OPTION_]...


== DESCRIPTION

The odgi extract(1) command extracts parts of the graph as defined by query criteria.


== OPTIONS

=== Graph Files IO

*-f, --input-graphs*=_FILE_::
  File containing the succinct variation graph. The file name usually ends with _.og_.

*-o, --out*=_FILE_::
  Store all  subgraph in this file. The file name usually ends with _.og_.


=== Extract Options

*-s, --split-subgraphs*=_STRING_::
    Instead of writing the target subgraphs into a single graph, write one subgraph per given target to a separate file named `path:start-end.og` (0-based coordinates).

*-l, --node-list*::_FILE_::
    A file with one node id per line. The node specified will be extracted from the input graph.

*-n, --node*::_STRING_::
    A single node from which to begin our traversal.

*-c, --context*::_NUMBER_::
    The number of steps away from our initial subgraph that we should collect.

*-L, --use-length*::
    Treat the context size as a length in bases (and not as a number of steps).

*-r, --path-range*::
    Find the node(s) in the specified path range TARGET=path[:pos1[-pos2]] (0-based coordinates)

*-r, --bed-file*::_FILE_::
    Find the node(s) in the path range(s) specified in the given BED FILE

*-E, --full-range*::
    Collects all nodes in the sorted order of the graph in the min and max position touched by the given path ranges.
    Be careful to use it with very complex graphs.

=== Threading

*-t, --threads*=_N_::
    Number of threads to use (to embed the subpaths in parallel).

=== Processing Information

*-P, --progress*::
  Print information to stderr.


=== Program Information

*-h, --help*::
  Print a help message for *odgi extract*.


== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/vgteam/odgi/issues.

== AUTHORS

*odgi extract* was written by Andrea Guarracino.

ifdef::backend-manpage[]
== RESOURCES

*Project web site:* https://github.com/vgteam/odgi

*Git source repository on GitHub:* https://github.com/vgteam/odgi

*GitHub organization:* https://github.com/vgteam

*Discussion list / forum:* https://github.com/vgteam/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]