= odgi overlap(1)
ifdef::backend-manpage[]
Andrea Guarracino
:doctype: manpage
:release-version: v0.6.0
:man manual: odgi overlap
:man source: odgi v0.6.0
:page-layout: base
endif::[]

== NAME

odgi_overlap - find the paths touched by the input paths


== SYNOPSIS

*odgi overlap* [*-i, --input*=_FILE_] [_OPTION_]...

== DESCRIPTION

The odgi overlap(1) command finds the paths touched by the input paths.


== OPTIONS

=== Graph Files IO

*-i, --input*=_FILE_::
  Perform the search in this graph.


=== Overlap Options

*-s, --subset-paths*=_FILE_::
  Perform the search considering only the paths specified in the FILE; the file must contain one path name per line and a
  subset of all paths can be specified.

*-r, --path*=_STRING_::
  Perform the search of the given path in the graph.

*-R, --paths*=_FILE_::
  Perform the search for the paths listed in FILE

*-b, --bed-input*=_FILE_::
  A BED file of ranges in paths in the graph.


=== Threading

*-t, --threads*=_N_::
  Number of threads to use.


=== Program Information

*-h, --help*::
  Print a help message for *odgi overlap*.


== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/pangenome/odgi/issues.

== AUTHORS

*odgi overlap* was written by Andrea Guarracino.

ifdef::backend-manpage[]
== RESOURCES

*Project web site:* https://github.com/pangenome/odgi

*Git source repository on GitHub:* https://github.com/pangenome/odgi

*GitHub organization:* https://github.com/pangenome

*Discussion list / forum:* https://github.com/pangenome/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]