= odgi draw(1)
ifdef::backend-manpage[]
Erik Garrison
:doctype: manpage
:release-version: v0.6.0
:man manual: odgi draw
:man source: odgi v0.6.0
:page-layout: base
endif::[]


== NAME

odgi_draw - variation graph visualizations in 2D


== SYNOPSIS

*odgi draw* [*-i, --idx*=_FILE_] [*-c, --coords-in*=_FILE_] [*-p, --png*=_FILE_] [_OPTION_]...


== DESCRIPTION

The odgi draw(1) command draws previously-determined 2D layouts of the graph with diverse annotations.

== OPTIONS

=== Files IO

*-i, --idx*=_FILE_::
  Load the graph from this file. The file name usually ends with _.og_.

*-c, --coords-in*=_FILE_::
  Read the layout coordinates from this .lay format file produced by <<odgi_layout.adoc#_odgi_layout1, odgi layout>>

*-T, --tsv*=_FILE_::
    Write the TSV layout plus displayed annotations to this file.

*-s, --svg*=_FILE_::
  Write an SVG rendering to this file.

*-p, --png*=_FILE_::
  Write a rasterized PNG rendering to this file.

=== Visualization Options

*-H, --png-height*=_N_::
  Height of PNG rendering (default: 1000).

*-E, --png-border*=_N_::
  Size of PNG border in bp (default: 10).

*-C --color-paths*::
  Color paths (in PNG output).

*-R, --scale*=_N_::
  Image scaling (default 1.0).

*-B, --border*=_N_::
  Image border (in approximate bp) (default 100.0).

*-w, --line-width*=_N_::
  Line width (in approximate bp) (default 0.0).

*-S, --path-line-spacing*=_N_::
  Spacing between path lines in png layout (in approximate bp) (default 0.0).

*-X, --path-index*=_FILE_::
  Load the path index from this file.

=== Program Information

*-h, --help*::
  Print a help message for *odgi draw*.


== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).


== BUGS

  Refer to the *odgi* issue tracker at https://github.com/pangenome/odgi/issues.


== AUTHORS

*odgi draw* was written by Erik Garrison.

ifdef::backend-manpage[]


== RESOURCES

*Project web site:* https://github.com/pangenome/odgi

*Git source repository on GitHub:* https://github.com/pangenome/odgi

*GitHub organization:* https://github.com/pangenome

*Discussion list / forum:* https://github.com/pangenome/odgi/issues


== COPYING

The MIT License (MIT)

Copyright (c) 2019-2021 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]