= odgi explode(1)
ifdef::backend-manpage[]
Andrea Guarracino
:doctype: manpage
:release-version: v0.6.0
:man manual: odgi explode
:man source: odgi v0.6.0
:page-layout: base
endif::[]

== NAME

odgi_explode - breaks a graph into connected components in their own files


== SYNOPSIS

*odgi explode* [*-i, --idx*=_FILE_] [*-p, --prefix*=_STRING_] [_OPTION_]...

== DESCRIPTION

The odgi explode(1) command breaks a graph into connected components, writing each component in its own file.


== OPTIONS

=== Graph Files IO

*-i, --idx*=_FILE_::
  File containing the succinct variation graph to break in its components. The file name usually ends with _.og_.


=== Explode Options

*-p, --prefix*=_STRING_::
  Write each connected component in a file with the given prefix. The file for the component `i` will be named
`STRING.i.og` (default: `component`)

*-O, --optimize*::
  Compact the node ID space in each connected component.

=== Threading

*-t, --threads*=_N_::
Number of threads to use (to write the components in parallel).


=== Processing Information

*-P, --progress*::
  Print information about the components and the progress to stderr.


=== Program Information

*-h, --help*::
  Print a help message for *odgi explode*.


== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; parameter error; file processing failure; unexpected error).

== BUGS

Refer to the *odgi* issue tracker at https://github.com/vgteam/odgi/issues.

== AUTHORS

*odgi explode* was written by Andrea Guarracino.

ifdef::backend-manpage[]
== RESOURCES

*Project web site:* https://github.com/vgteam/odgi

*Git source repository on GitHub:* https://github.com/vgteam/odgi

*GitHub organization:* https://github.com/vgteam

*Discussion list / forum:* https://github.com/vgteam/odgi/issues

== COPYING

The MIT License (MIT)

Copyright (c) 2019 Erik Garrison

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
endif::[]