all: stringology2019.pdf

clean:
	rm -f stringology2019.aux stringology2019.log stringology2019.nav stringology2019.out stringology2019.pdf stringology2019.snm stringology2019.toc stringology2019.vrb

.PHONY: clean

stringology2019.pdf: stringology2019.tex
	pdflatex stringology2019.tex
	pdflatex stringology2019.tex
